version: '3'
services:
  app:
    build: .
    container_name: merch-api
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    command: ["go", "run", "cmd/server/main.go"]
    depends_on:
      - postgres
    networks:
      - go_net

  postgres:
    image: postgres:13
    container_name: merch-db
    environment:
      POSTGRES_USER: merchuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: merchdb
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - go_net

networks:
  go_net:
    driver: bridge

volumes:
  db_data: